# Generated by Django 5.2.13 on 2026-04-19 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(help_text='Masalan: venue, media, decor — frontend categoryId bilan mos.', max_length=32, primary_key=True, serialize=False, verbose_name='kod (id)')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='URL slug')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('short_label', models.CharField(max_length=64, verbose_name='qisqa nom')),
                ('subtitle', models.TextField(blank=True, verbose_name='tagline')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='ikonka (masalan ph-buildings)')),
                ('search_hint', models.CharField(blank=True, max_length=255, verbose_name='qidiruv yordami')),
                ('zone', models.CharField(choices=[('primary', 'Asosiy qator (bosh sahifa 1-qator)'), ('extra', 'Qo‘shimcha qator (2-qator)')], default='primary', max_length=16, verbose_name='joylashuv')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['zone', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PromoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('badge', models.CharField(blank=True, max_length=64, verbose_name='badge')),
                ('title', models.CharField(max_length=255, verbose_name='sarlavha')),
                ('path', models.CharField(max_length=255, verbose_name='yo‘nalish (masalan /category/toyxona)')),
                ('background_url', models.URLField(max_length=2048, verbose_name='fon rasm URL')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='ko‘rishlar')),
                ('is_active', models.BooleanField(default=True, verbose_name='faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promo post',
                'verbose_name_plural': 'Promo postlar',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, verbose_name='to‘liq ism')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Frontend va URL uchun barqaror identifikator.', max_length=64, unique=True, verbose_name='tashqi id (masalan v-versal)')),
                ('slug', models.SlugField(max_length=128, verbose_name='URL slug')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('district', models.CharField(blank=True, max_length=128, verbose_name='tuman')),
                ('image', models.URLField(max_length=2048, verbose_name='asosiy rasm URL')),
                ('gallery', models.JSONField(blank=True, default=list, verbose_name='galereya (URL ro‘yxati)')),
                ('price_label', models.CharField(blank=True, max_length=64, verbose_name='narx')),
                ('price_note', models.CharField(blank=True, max_length=64, verbose_name='narx izohi')),
                ('badge', models.CharField(blank=True, max_length=32, null=True, verbose_name='badge (Top, Yangi…)')),
                ('footer_line', models.CharField(blank=True, max_length=128, verbose_name='pastki qator')),
                ('footer_icon', models.CharField(blank=True, max_length=64, verbose_name='ikonka klass')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='telefon')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='telegram')),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2, verbose_name='reyting')),
                ('review_count_cached', models.PositiveIntegerField(default=0, help_text='Avtomatik yangilanadi (sharhlar qo‘shilganda).', verbose_name='sharhlar soni (cache)')),
                ('tagline', models.CharField(blank=True, max_length=512, verbose_name='tagline')),
                ('location', models.CharField(blank=True, max_length=512, verbose_name='manzil')),
                ('description', models.TextField(blank=True, verbose_name='tavsif')),
                ('specs', models.JSONField(blank=True, default=list, verbose_name='texnik jadval [{label, value}]')),
                ('is_published', models.BooleanField(default=True, verbose_name='saytda ko‘rinsin')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ichki tartib')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='catalog.category', verbose_name='kategoriya')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendorlar',
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HomePlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('top_venues', 'Top to‘yxonalar'), ('recommended', 'Tavsiya qilamiz')], max_length=32, verbose_name='bo‘lim')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='tartib')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_placements', to='catalog.vendor', verbose_name='vendor')),
            ],
            options={
                'verbose_name': 'Bosh sahifa joylashuvi',
                'verbose_name_plural': 'Bosh sahifa joylashuvlari',
                'ordering': ['section', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='VendorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=128, verbose_name='muallif')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='baho (1–5)')),
                ('text', models.TextField(verbose_name='matn')),
                ('date', models.DateField(blank=True, null=True, verbose_name='sana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.vendor', verbose_name='vendor')),
            ],
            options={
                'verbose_name': 'Sharh',
                'verbose_name_plural': 'Sharhlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['category', 'is_published'], name='catalog_ven_categor_c78b55_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeplacement',
            constraint=models.UniqueConstraint(fields=('section', 'vendor'), name='uniq_home_section_vendor'),
        ),
    ]
