# Generated by Django 5.2.13 on 2026-04-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_vendor_image_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='ko‘rishlar soni'),
        ),
    ]
