# Generated by Django 5.2.13 on 2026-04-23 12:15

from django.db import migrations


def update_view_counts(apps, schema_editor):
    Vendor = apps.get_model('catalog', 'Vendor')
    for v in Vendor.objects.all():
        # Formula from frontend: v.reviewCount * 121 + 142
        v.view_count = (v.review_count_cached * 121) + 142
        v.save(update_fields=['view_count'])

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_vendor_view_count'),
    ]

    operations = [
        migrations.RunPython(update_view_counts),
    ]
