# Generated by Django 5.2.13 on 2026-04-23 13:07

from django.db import migrations


def fix_category_names(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    mapping = {
        "venue": "To'yxona",
        "media": "FotoStudio",
        "attire": "Kelin va kuyov liboslari",
        "transport": "Kartej",
        "mc": "Honanda",
        "decor": "Dekor va zal bezatish",
        "marryme": "Marry me joy va taklif",
    }
    for code, name in mapping.items():
        Category.objects.filter(pk=code).update(title=name, short_label=name)

class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_vendor_category'),
    ]

    operations = [
        migrations.RunPython(fix_category_names),
    ]
