# Generated by Django 5.2.11 on 2026-04-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_view_counts'),
        ('catalog', '0011_fix_category_titles_uz'),
    ]

    operations = [
    ]
