# Generated by Django 5.2.14 on 2026-05-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_merge_20260425_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=32, verbose_name='telefon')),
                ('code', models.CharField(max_length=6, verbose_name='OTP kod')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram chat ID')),
                ('reg_token', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='reg token (OTP tasdiqlangandan keyin)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='amal qilish muddati')),
                ('is_used', models.BooleanField(default=False, verbose_name='ishlatilgan')),
            ],
            options={
                'verbose_name': 'Telefon OTP',
                'verbose_name_plural': 'Telefon OTPlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='kenglik (latitude)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='uzunlik (longitude)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='map_link',
            field=models.URLField(blank=True, help_text='Yandex Maps yoki Google Maps havolasi. Avtomatik lat/lng ajratiladi.', max_length=2048, verbose_name='Xarita havolasi (Yandex/Google Maps)'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='story_video_url',
            field=models.URLField(blank=True, help_text='Top to’yxonalar story popup uchun YouTube link.', max_length=2048, verbose_name='story video URL (YouTube)'),
        ),
    ]
